---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

version: '3.7'

services:
  vault:
    image: 'vault:latest'
    command: 'server'
    cap_add:
    - 'IPC_LOCK'
    restart: 'unless-stopped'
    volumes:
    - type: 'bind'
      source: '/var/log/vault'
      target: '/vault/logs'
    - type: 'bind'
      source: '/etc/vault'
      target: '/vault/config'
    - type: 'volume'
      source: 'files'
      target: '/vault/file'
    hostname: '$HOSTNAME.$DOMAIN'
    networks:
    - 'traefik'
    container_name: 'vault'
    labels:
    - 'traefik.enable=true'
    - 'traefik.http.routers.vault.rule=Host(`$HOSTNAME.$DOMAIN`)'
    - 'traefik.http.routers.vault.entrypoints=websecure'
    - 'traefik.http.routers.vault.middlewares=$MIDDLEWARE'
    - 'traefik.http.routers.vault.service=vault'
    - 'traefik.http.services.vault.loadbalancer.passhostheader=true'

volumes:
  files: {}

networks:
  traefik:
    external: true
